### ISSUE TITLE
.all() method doesn't sync with the new added records in the database

### ISSUE THREAD

**Issue by Anas-Nabulsi** [DablioZe/SecureDB#2]
Thank you for the great library!

So I'm trying to reflect real-time change upon adding a new record/item to the database. So upon adding the item I retrigger the function db.all(). But it gets the old data that doesn't include the new record added.

How to sync?

**Comment by Anas-Nabulsi** [comment]
I should have used async/await
```
async function getData(){
    return await db.all();
  }
```
It's working fine now

**Comment by DablioZe** [comment]
> I should have used async/await
> ```
> async function getData(){
>     return await db.all();
>   }
> ```
> It's working fine now

- Thanks for letting me know this problem, I will build an optimized solution and I will solve it. Sorry for the inconvenience.
